DROP TABLE IF EXISTS animals;

CREATE TABLE animals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    species TEXT NOT NULL,
    age INTEGER NOT NULL,
    image_url TEXT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);